-- Die 7 Werbekunden (Stand Sept. 2026). Änderungen später im Admin-Panel.
INSERT OR IGNORE INTO sponsors (id,name,image,headline_de,headline_tr,headline_en,cta_de,cta_tr,cta_en,link_web,link_wa,link_tel,link_ig,places,kieze,cats,priority,own,plan,contact,start_at,end_at,active,created_at,updated_at) VALUES
('deindigitalerhelfer','Dein Digitaler Helfer','/assets/sponsors/deindigitalerhelfer.webp',
 'Behördenbriefe verstehen, Anträge vorbereiten','Resmi yazıları anla, başvuruları hazırla','Understand official letters, prepare applications',
 'Kostenlos starten','Ücretsiz başla','Start for free','https://deindigitalerhelfer.com','','','',
 'slider,native,quiz','','service',5,1,'own','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('ersenbox','ErsenBox','/assets/sponsors/ersenbox.webp',
 'Dokumente verstehen, Risiken erkennen','Belgeleri anla, riskleri gör','Understand documents, spot risks',
 'Mehr erfahren','Keşfet','Learn more','https://ersenbox.com','','','',
 'slider,native','','',3,1,'own','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('deinfinanzenhelfer','Dein Finanzen Helfer','/assets/sponsors/deinfinanzenhelfer.webp',
 'Finanzamt-Brief verstehen, Steuererklärung online','Finanzamt mektubunu anla, vergi beyannamesi online','Understand tax office letters, file online',
 'Anfrage starten','Başvur','Get started','https://deinfinanzenhelfer.com','','','',
 'slider,native,quiz','','service',3,1,'own','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('it-rechtbox','IT-Rechtbox','/assets/sponsors/it-rechtbox.webp',
 'Website prüfen: Impressum, Datenschutz, Cookies','Web siteni kontrol et: Impressum, Datenschutz, çerezler','Check your website: imprint, privacy, cookies',
 'Website prüfen','Siteyi kontrol et','Check website','https://it-rechtbox.pages.dev','','','',
 'slider,native,after_submit','','',4,1,'own','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('tek-getraenke','Terra Verde TEK Getränke','/assets/sponsors/tek-getraenke.webp',
 'Getränke, Lebensmittel & Verpackung im Großhandel – privat und gewerblich','İçecek, gıda ve ambalajda toptan satış – bireysel ve işletmelere','Wholesale drinks, food & packaging – private and business',
 'Sortiment ansehen','Ürünleri gör','See products','https://www.tekgetraenke.de','','','https://www.instagram.com/terraverdegetraenke/',
 'slider,native','','markt,shop,restaurant,imbiss,cafe',6,0,'intro19','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('the-visit','The Visit Coffee Roastery','/assets/sponsors/the-visit.webp',
 'Kaffeerösterei in Kreuzberg','Kreuzberg''de kahve kavurma evi','Coffee roastery in Kreuzberg',
 'Website ansehen','Siteye git','Visit website','https://thevisitcoffeeroastery.pages.dev/','','','',
 'slider,native','kreuzberg','cafe,fruehstueck',6,0,'intro19','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000),
('berlin-handel','Berlin Handel','/assets/sponsors/berlin-handel.webp',
 'Getränke-Lieferservice für Berlin & Umgebung – Bestellung per WhatsApp','Berlin ve çevresine içecek teslimatı – WhatsApp ile sipariş','Drinks delivery in Berlin & surroundings – order via WhatsApp',
 'WhatsApp bestellen','WhatsApp ile sipariş','Order on WhatsApp','','https://wa.me/4915126509586','tel:+4915126509586','',
 'slider,native,quiz','','',6,0,'intro19','',0,0,1,strftime('%s','now')*1000,strftime('%s','now')*1000);
